// Real browser checks for dock motion, wheel isolation and portable graph packages.
import assert from 'node:assert/strict'
import { pathToFileURL } from 'node:url'
import { resolve } from 'node:path'
import { unzipSync } from 'fflate'
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(resolve(process.env.PLAYWRIGHT_MODULE)).href : 'playwright')
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH ?? 'chromium', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, acceptDownloads: true })
const errors = []
page.on('pageerror', (error) => errors.push(error.message))
const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0S8AAAAASUVORK5CYII='
const zoom = () => page.evaluate(() => window.workspaceRt.area.area.transform.k)
const activeId = () => page.evaluate(() => window.workspaceSession.graphSession.id)
const waitForNewGraph = (id) => page.waitForFunction((id) => window.workspaceSession.graphSession.id !== id && !document.querySelector('.topbar button[title="导入 .astelier 图包"]').disabled, id)
async function dropArchive(target, bytes) {
  await target.evaluate((el, bytes) => {
    const transfer = new DataTransfer()
    transfer.items.add(new File([Uint8Array.from(bytes)], 'example.astelier', { type: 'application/zip' }))
    el.dispatchEvent(new DragEvent('dragover', { bubbles: true, cancelable: true, dataTransfer: transfer }))
    el.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: transfer }))
  }, [...bytes])
}
async function previewArchive(target, bytes, protectedNames = false) {
  await target.evaluate((el, { bytes, protectedNames }) => {
    const transfer = new DataTransfer()
    transfer.items.add(new File([Uint8Array.from(bytes)], 'example.astelier', { type: protectedNames ? '' : 'application/zip' }))
    if (protectedNames) Object.defineProperty(transfer, 'files', { value: new DataTransfer().files })
    const bounds = el.getBoundingClientRect()
    el.dispatchEvent(new DragEvent('dragover', { bubbles: true, cancelable: true, dataTransfer: transfer, clientX: bounds.x + bounds.width / 2, clientY: bounds.y + bounds.height / 2 }))
  }, { bytes: [...bytes], protectedNames })
}
try {
  await page.goto(process.env.ASTELIER_TEST_URL ?? 'http://127.0.0.1:5173')
  await page.waitForFunction(() => document.querySelector('.run-btn') && !document.querySelector('.run-btn').disabled)
  await page.evaluate(async () => { window.workspaceRt = (await import('/src/canvas/runtime.ts')).rt; window.workspaceSession = await import('/src/canvas/session.svelte.ts') })
  const head = await page.locator('.sidebar-head').boundingBox(), top = await page.locator('.topbar').boundingBox()
  assert.equal(head.y + head.height, top.y + top.height)
  const sidebarWidth = await page.locator('#workspace-sidebar').evaluate((el) => el.getBoundingClientRect().width)
  assert.equal(await page.getByRole('button', { name: '管理后端', exact: true }).count(), 1)
  assert.equal(await page.getByRole('button', { name: '设置', exact: true }).count(), 0)
  await page.locator('.sidebar .tree-row').first().click({ button: 'right' })
  await page.getByRole('menu').waitFor()
  await page.getByRole('button', { name: '收起侧栏', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('#workspace-sidebar').getBoundingClientRect().width === 0)
  assert.equal(await page.locator('.topbar .sidebar-toggle + .source-entry').count(), 1, 'collapsed sidebar should not add a decorative button-like logo')
  await page.getByRole('menu').waitFor({ state: 'detached' })
  assert.equal(await page.locator('.main').evaluate((el) => el.getBoundingClientRect().x), 0)
  assert.equal(await page.getByRole('button', { name: '管理后端', exact: true }).count(), 1)
  await page.getByRole('button', { name: '管理后端', exact: true }).click()
  await page.getByRole('dialog', { name: '设置', exact: true }).getByRole('button', { name: '关闭', exact: true }).click()
  await page.reload()
  await page.waitForFunction(() => document.querySelector('.run-btn') && !document.querySelector('.run-btn').disabled)
  await page.getByRole('button', { name: '展开侧栏', exact: true }).click()
  await page.waitForFunction((width) => document.querySelector('#workspace-sidebar').getBoundingClientRect().width === width, sidebarWidth)
  assert.equal(await page.getByRole('button', { name: '管理后端', exact: true }).count(), 1)
  await page.evaluate(async () => { window.workspaceRt = (await import('/src/canvas/runtime.ts')).rt; window.workspaceSession = await import('/src/canvas/session.svelte.ts') })
  console.log('PASS sidebar collapse/restore persists, keeps its width and dismisses menus; one reachable management entry')
  const collapse = page.getByRole('button', { name: '收起面板', exact: true })
  const handle = await collapse.boundingBox()
  const dockHead = await page.locator('.dock-head').boundingBox()
  assert(Math.abs(handle.x + handle.width / 2 - 720) < 1)
  assert(handle.y >= dockHead.y && handle.y + handle.height <= dockHead.y + dockHead.height, 'library toggle belongs inside the first header row')
  await collapse.evaluate((el) => window.savedLibraryToggle = el)
  assert.equal(await page.locator('.dock').evaluate((el) => getComputedStyle(el).transitionDuration.split(',')[0]), '0.22s')
  await page.screenshot({ path: '/tmp/astelier-dock-expanded.png' })
  await collapse.click()
  await page.waitForFunction(() => document.querySelector('.dock').offsetHeight === 22)
  const rail = await page.getByRole('button', { name: '展开面板', exact: true }).boundingBox()
  assert(Math.abs(rail.x + rail.width / 2 - 720) < 1)
  assert(Math.abs(rail.y + rail.height - 1000) < 1)
  assert.equal(await page.getByRole('button', { name: '展开面板', exact: true }).evaluate((el) => el === window.savedLibraryToggle), true)
  await page.screenshot({ path: '/tmp/astelier-dock-collapsed.png' })
  await page.getByRole('button', { name: '展开面板', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.dock')?.offsetHeight === 320)
  assert.equal(await page.getByRole('button', { name: '收起面板', exact: true }).evaluate((el) => el === window.savedLibraryToggle), true)
  console.log('PASS aligned app header; centered dock collapse/expand and animated height restoration')

  const prompt = page.locator('.prompt-wrap textarea')
  await prompt.fill(Array.from({ length: 40 }, (_, i) => `Line ${i}`).join('\n'))
  await prompt.evaluate((el) => el.scrollTop = el.scrollHeight)
  await prompt.hover()
  const before = await zoom()
  await page.mouse.wheel(0, 200)
  await page.waitForTimeout(100)
  assert.equal(await zoom(), before)
  await prompt.evaluate((el) => el.scrollTop = 0)
  await page.mouse.wheel(0, -200)
  await page.waitForTimeout(100)
  assert.equal(await zoom(), before)
  await prompt.fill('Short prompt')
  await page.mouse.wheel(0, 200)
  await page.waitForTimeout(100)
  assert.equal(await zoom(), before)
  const canvas = await page.locator('#rete').boundingBox()
  await page.mouse.move(canvas.x + 20, canvas.y + 20)
  await page.mouse.wheel(0, 200)
  await page.waitForFunction((before) => window.workspaceRt.area.area.transform.k !== before, before)
  console.log('PASS prompt wheel stays isolated at both boundaries and without overflow; canvas wheel still zooms')

  const sourceId = await page.evaluate(async (png) => {
    const r = await import('/src/backends/registry.svelte.ts')
    const session = await import('/src/canvas/session.svelte.ts')
    await session.flushNow()
    const store = r.backendStore('local'), graph = await store.createGraph(null, '可分享的图')
    const bytes = Uint8Array.from(atob(png), (c) => c.charCodeAt(0))
    const reference = await store.uploadGraphStoreFile(graph.id, '参考.png', new Blob([bytes], { type: 'image/png' }))
    await store.uploadGraphStoreFile(graph.id, '未引用.png', new Blob([bytes], { type: 'image/png' }))
    await store.putGraph(graph.id, { version: 1, nodes: [{ id: 'reference', type: 'image', params: { images: [{ file: reference.name, name: '原始参考图', w: 1, h: 1 }] } }], edges: [] })
    await store.putView(graph.id, { version: 1, positions: { reference: { x: 60, y: 80 } }, viewport: { x: 20, y: 30, zoom: 1 } })
    r.backend('local').revision++
    await session.openGraph({ backendId: 'local', id: graph.id })
    return graph.id
  }, png)
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出图', exact: true }).click()
  const download = await downloadEvent
  assert.equal(download.suggestedFilename(), '可分享的图.astelier')
  const stream = await download.createReadStream(), chunks = []
  for await (const chunk of stream) chunks.push(chunk)
  const zipped = Buffer.concat(chunks), entries = unzipSync(zipped)
  assert.deepEqual(Object.keys(entries).sort(), ['graph.json', 'view.json', 'store/', 'store/参考.png', 'store/未引用.png'].sort())
  const archivedGraph = JSON.parse(new TextDecoder().decode(entries['graph.json']))
  assert.equal(archivedGraph.id, sourceId)
  assert(!Object.keys(entries).some((path) => /config|stores\//.test(path)))

  await previewArchive(page.locator('#rete'), zipped, true)
  const hint = page.locator('.archive-drop-preview')
  await hint.getByText('松手导入图包', { exact: true }).waitFor()
  assert.equal(await hint.locator('.destination').innerText(), '浏览器存储 › 根目录')
  assert.equal(await hint.locator('small').innerText(), '.astelier 图包')
  assert.equal(await page.locator('.sidebar .backend-root.archive-target').count(), 1)
  await page.screenshot({ path: '/tmp/astelier-graph-drop-main.png' })
  await page.keyboard.press('Escape')
  await hint.waitFor({ state: 'detached' })
  await previewArchive(page.locator('.sidebar .roots'), zipped)
  assert.equal(await page.locator('.archive-drop-preview.sidebar-preview .destination').innerText(), '浏览器存储 › 根目录')
  await page.keyboard.press('Escape')
  await hint.waitFor({ state: 'detached' })
  // Regular image drags must retain their own image-node/library feedback.
  await page.locator('#rete').evaluate((el) => {
    const transfer = new DataTransfer()
    transfer.items.add(new File(['image'], 'image.png', { type: 'image/png' }))
    el.dispatchEvent(new DragEvent('dragover', { bubbles: true, cancelable: true, dataTransfer: transfer }))
  })
  assert.equal(await hint.count(), 0)

  await page.waitForFunction(() => !document.querySelector('.topbar button[title="导入 .astelier 图包"]').disabled)
  // Drop over the image library: the archive must import as a graph, not as a picture.
  await dropArchive(page.locator('.dock'), zipped)
  await waitForNewGraph(sourceId)
  const importedId = await activeId()
  const restored = await page.evaluate(async ({ importedId, sourceId }) => {
    const store = (await import('/src/backends/registry.svelte.ts')).backendStore('local')
    return { graph: await store.fetchGraph(importedId), view: await store.fetchView(importedId), assets: await store.listGraphStoreFiles(importedId), source: await store.fetchGraph(sourceId), library: await store.storeTree() }
  }, { importedId, sourceId })
  assert.notEqual(importedId, sourceId)
  assert.deepEqual(restored.graph.nodes, archivedGraph.nodes)
  assert.deepEqual(restored.view, JSON.parse(new TextDecoder().decode(entries['view.json'])))
  assert.equal(restored.assets.length, 2)
  assert.equal(restored.library.files.length, 0)
  assert.equal(restored.source.id, sourceId)
  await page.locator('.image-editor img').first().waitFor()

  await page.getByRole('button', { name: '导入图', exact: true }).click()
  await page.locator('input[accept=".astelier"]').setInputFiles({ name: 'copy.astelier', mimeType: 'application/zip', buffer: zipped })
  await waitForNewGraph(importedId)
  const secondId = await activeId()
  const groupId = await page.evaluate(async () => {
    const r = await import('/src/backends/registry.svelte.ts'), group = await r.backendStore('local').createGroup('导入目标', null)
    r.backend('local').revision++
    return group.id
  })
  const folderRow = page.locator(`.sidebar [data-row-id="${groupId}"]`)
  await folderRow.waitFor()
  const folderBefore = await folderRow.boundingBox()
  await previewArchive(folderRow, zipped)
  await hint.getByText('松手导入图包', { exact: true }).waitFor()
  assert.equal(await hint.locator('.destination').innerText(), '浏览器存储 › 导入目标')
  assert.equal(await hint.locator('small').innerText(), 'example.astelier')
  assert.equal(await folderRow.evaluate((el) => el.classList.contains('archive-folder')), true)
  assert.deepEqual(await folderRow.boundingBox(), folderBefore, 'drop preview should not shift the target row')
  await page.screenshot({ path: '/tmp/astelier-graph-drop-sidebar.png' })
  await folderRow.evaluate((el) => el.dispatchEvent(new DragEvent('dragend', { bubbles: true })))
  await hint.waitFor({ state: 'detached' })
  await dropArchive(page.locator(`.sidebar [data-row-id="${groupId}"]`), zipped)
  await waitForNewGraph(secondId)
  assert.equal(await page.evaluate(async () => {
    const r = await import('/src/backends/registry.svelte.ts'), s = await import('/src/canvas/session.svelte.ts')
    return (await r.backendStore('local').fetchGraph(s.graphSession.id)).group_id
  }), groupId)
  await page.screenshot({ path: '/tmp/astelier-workspace-ui.png' })
  assert.deepEqual(errors, [])
  console.log('PASS .astelier download contains the complete graph directory; drag/picker import copies all resources; folder drop targets its group')
  console.log('PASS drag previews show the storage/folder for protected OS file drags, clear on cancel/end and leave target rows in place')
} catch (error) {
  await page.screenshot({ path: '/tmp/astelier-workspace-ui-failure.png' })
  console.error('Browser errors:', errors)
  throw error
} finally { await browser.close() }
