// OpenAI Images 协议参数表（gpt-image 系）。
// Generate 节点直接针对协议设计：无论接入什么模型（model 是开集合），
// 参数面板恒定；模型不支持的值由服务端按档案校验报错或由网关裁决。
// 高级参数默认折叠；「默认」（未设置）= 不随请求发送。
import type { ParamDef } from './profiles'

export const OPENAI_IMAGE_PARAMS: ParamDef[] = [
	{
		key: 'quality',
		label: '画质',
		kind: 'select',
		options: ['auto', 'high', 'medium', 'low', 'xhigh', 'max'],
		min: null,
		max: null,
		advanced: false,
		group: '',
	},
	{
		key: 'size',
		label: '尺寸',
		kind: 'size',
		// 常用预设建议；gpt-image-2+ 支持任意 16 整除的自定义 WxH，可自由输入
		options: ['auto', '1024x1024', '1536x1024', '1024x1536', '1792x1008', '1008x1792'],
		min: null,
		max: null,
		advanced: false,
		group: '',
	},
	{
		key: 'n',
		label: '数量',
		kind: 'number',
		options: [],
		min: 1,
		max: 10,
		advanced: false,
		group: '',
	},
	{
		key: 'background',
		label: '背景',
		kind: 'select',
		options: ['auto', 'transparent', 'opaque'],
		min: null,
		max: null,
		advanced: false,
		group: '',
	},
	{
		key: 'output_format',
		label: '输出格式',
		kind: 'select',
		options: ['png', 'jpeg', 'webp'],
		min: null,
		max: null,
		advanced: false,
		group: 'output',
	},
	{
		key: 'input_fidelity',
		label: '原图保真',
		kind: 'select',
		options: ['low', 'high'],
		min: null,
		max: null,
		advanced: true,
		group: 'edit',
	},
	{
		key: 'output_compression',
		label: '压缩率',
		kind: 'number',
		options: [],
		min: 0,
		max: 100,
		advanced: true,
		group: 'output',
	},
	{
		key: 'moderation',
		label: '审核',
		kind: 'select',
		options: ['auto', 'low'],
		min: null,
		max: null,
		advanced: true,
		group: 'safety',
	},
	{
		key: 'user',
		label: '用户标识',
		kind: 'text',
		options: [],
		min: null,
		max: null,
		advanced: true,
		group: 'safety',
	},
]
