// OpenAI Images 协议参数表（gpt-image 系）。
// 与后端 src/profiles.rs 的档案同源（当前为镜像维护；权威默认值在后端
// ParamDef.default_value，前端展示与「始终完整发送」init 以这里为准，
// 后端 launch_run 也会按档案兜底补齐）。
// UI 不再提供「默认」占位：每个参数始终有具体值，缺失键按 def 归一。
import type { ParamDef } from './profiles'

export const OPENAI_IMAGE_PARAMS: ParamDef[] = [
	{
		key: 'quality',
		label: '画质',
		kind: 'select',
		control: 'slider',
		options: ['auto', 'high', 'medium', 'low', 'xhigh', 'max'],
		min: null,
		max: null,
		advanced: false,
		group: '',
		def: 'auto',
	},
	{
		key: 'size',
		label: '尺寸',
		kind: 'size',
		// 常用预设建议；gpt-image-2+ 支持任意 16 整除的自定义 WxH，可自由输入
		options: ['auto', '1024x1024', '1536x1024', '1024x1536', '1792x1008', '1008x1792'],
		min: null,
		max: null,
		advanced: false,
		group: '',
		def: 'auto',
	},
	{
		key: 'n',
		label: '数量',
		kind: 'number',
		options: [],
		min: 1,
		max: 10,
		advanced: false,
		group: '',
		def: 1,
	},
	{
		key: 'background',
		label: '背景',
		kind: 'select',
		control: 'segmented',
		options: ['auto', 'transparent', 'opaque'],
		min: null,
		max: null,
		advanced: false,
		group: '',
		def: 'auto',
	},
	{
		key: 'output_format',
		label: '输出格式',
		kind: 'select',
		control: 'segmented',
		options: ['png', 'jpeg', 'webp'],
		min: null,
		max: null,
		advanced: false,
		group: 'output',
		def: 'png',
	},
	{
		key: 'input_fidelity',
		label: '原图保真',
		kind: 'select',
		options: ['low', 'high'],
		min: null,
		max: null,
		advanced: true,
		group: 'edit',
		def: 'low',
	},
	{
		key: 'output_compression',
		label: '压缩率',
		kind: 'number',
		options: [],
		min: 0,
		max: 100,
		advanced: true,
		group: 'output',
		def: 100,
	},
	{
		key: 'moderation',
		label: '审核',
		kind: 'select',
		options: ['auto', 'low'],
		min: null,
		max: null,
		advanced: true,
		group: 'safety',
		def: 'auto',
	},
]